- hosts: loadbalancer
  vars_files:
      - haproxy_var.yml

  tasks:
    - name: Installing HAProxy software 
      package:
          name: "haproxy"
          state: present
    - name: Parsing the haproxy config file and copying in the loadbalancer node      
      template:
          src: "/ansible-ws/ha-proxy/haproxy.cfg.j2"
          dest: "/etc/haproxy/"
    - name: Starting haproxy service
      service:
          name: haproxy
          state: started

